/**
 * Feature documentation generator (P1).
 *
 * Turns the feature-clustered graph into navigable docs:
 *   - README.md          index: overview, feature table, and a Mermaid map
 *                        of how features depend on each other.
 *   - features/<key>.md  one page per feature: summary, stats, routes,
 *                        depends-on / used-by, key files, Mermaid flow.
 *   - features.json      machine-readable manifest for AI agents / CI.
 *
 * Pure and deterministic (no timestamps) so output is testable and produces
 * clean diffs when regenerated.
 */
import type { OmniGraph, OmniNode, FeatureGroup, FeatureModel } from '../types';
import { detectFeatures } from './feature-detector';

export interface DocFile {
  /** Path relative to the output directory */
  path: string;
  content: string;
}

const SHARED_ID = '__shared';

// ─── Small helpers ──────────────────────────────────────────────────

/** Strip the "feature-" id prefix to get a filename-safe key */
function keyOf(feature: FeatureGroup): string {
  return feature.id.replace(/^feature-/, '');
}

/** Escape a cell for a Markdown table */
function cell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** A Mermaid-safe quoted label */
function mlabel(s: string): string {
  return s.replace(/"/g, "'").replace(/[\r\n]+/g, ' ');
}

/** Stable per-diagram id allocator (n0, n1, …) */
function mermaidIds() {
  const map = new Map<string, string>();
  return (key: string) => {
    if (!map.has(key)) map.set(key, 'n' + map.size);
    return map.get(key)!;
  };
}

function routeText(n: OmniNode): string {
  return n.metadata.route || n.metadata.path || '';
}

// ─── Cross-feature dependency computation ───────────────────────────

interface CrossDeps {
  dependsOn: Map<string, number>; // featureId → edge count (this → other)
  usedBy: Map<string, number>;    // featureId → edge count (other → this)
}

function computeCrossDeps(
  graph: OmniGraph,
  featureByNode: Map<string, string>,
): Map<string, CrossDeps> {
  const deps = new Map<string, CrossDeps>();
  const ensure = (id: string) => {
    if (!deps.has(id)) deps.set(id, { dependsOn: new Map(), usedBy: new Map() });
    return deps.get(id)!;
  };
  for (const e of graph.edges) {
    const s = featureByNode.get(e.source);
    const t = featureByNode.get(e.target);
    if (!s || !t || s === t) continue;
    if (s === SHARED_ID || t === SHARED_ID) continue;
    const sd = ensure(s);
    sd.dependsOn.set(t, (sd.dependsOn.get(t) ?? 0) + 1);
    const td = ensure(t);
    td.usedBy.set(s, (td.usedBy.get(s) ?? 0) + 1);
  }
  return deps;
}

/** Sort a featureId→count map into [featureId, count] pairs, desc by count */
function rankDeps(m: Map<string, number>): Array<[string, number]> {
  return [...m.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

// ─── Renderers ──────────────────────────────────────────────────────

function summarize(f: FeatureGroup): string {
  const bits: string[] = [`**${f.stats.nodes}** file${f.stats.nodes === 1 ? '' : 's'}`];
  if (f.stats.routes) bits.push(`**${f.stats.routes}** route${f.stats.routes === 1 ? '' : 's'}`);
  if (f.stats.entities) bits.push(`**${f.stats.entities}** data entit${f.stats.entities === 1 ? 'y' : 'ies'}`);
  return `The **${f.name}** feature spans ${bits.join(', ')}.`;
}

function renderIndex(
  model: FeatureModel,
  nameById: Map<string, string>,
  deps: Map<string, CrossDeps>,
): string {
  const L: string[] = [];
  L.push('# Feature Map');
  L.push('');
  L.push('_Auto-generated by OmniGraph. Regenerate with `omnigraph docs`._');
  L.push('');
  const totalNodes = model.features.reduce((a, f) => a + f.stats.nodes, 0);
  L.push(`**${model.features.length}** features · **${totalNodes}** grouped files · ` +
    `**${model.shared.length}** shared · **${model.ungrouped.length}** ungrouped`);
  L.push('');

  // ── Feature dependency map (Mermaid) ──
  L.push('## How features connect');
  L.push('');
  const edges: Array<[string, string, number]> = [];
  for (const [fid, d] of deps) {
    for (const [tid, c] of d.dependsOn) edges.push([fid, tid, c]);
  }
  if (edges.length === 0) {
    L.push('_No cross-feature dependencies detected._');
  } else {
    // Thin out noise on large graphs
    const threshold = model.features.length > 25 ? 2 : 1;
    const shown = edges.filter(([, , c]) => c >= threshold).sort((a, b) => b[2] - a[2]);
    const id = mermaidIds();
    const involved = new Set<string>();
    for (const [s, t] of shown) { involved.add(s); involved.add(t); }
    L.push('```mermaid');
    L.push('flowchart LR');
    for (const fid of involved) {
      const f = nameById.get(fid) ?? fid;
      L.push(`  ${id(fid)}["${mlabel(f)}"]`);
    }
    for (const [s, t, c] of shown) {
      L.push(`  ${id(s)} -->|${c}| ${id(t)}`);
    }
    L.push('```');
    if (threshold > 1) {
      L.push('');
      L.push(`_Showing dependencies with ≥ ${threshold} edges to reduce clutter._`);
    }
  }
  L.push('');

  // ── Feature table ──
  L.push('## Features');
  L.push('');
  L.push('| Feature | Files | Routes | Depends on |');
  L.push('| --- | ---: | ---: | --- |');
  for (const f of model.features) {
    const d = deps.get(f.id);
    const dependsOn = d
      ? rankDeps(d.dependsOn).map(([id]) => nameById.get(id) ?? id).slice(0, 5).join(', ')
      : '';
    L.push(`| [${cell(f.name)}](features/${keyOf(f)}.md) | ${f.stats.nodes} | ${f.stats.routes} | ${cell(dependsOn)} |`);
  }
  L.push('');
  return L.join('\n');
}

function featureFlowchart(
  feature: FeatureGroup,
  nodeById: Map<string, OmniNode>,
  featureByNode: Map<string, string>,
  nameById: Map<string, string>,
  downstream: Map<string, string[]>,
): string[] {
  const memberSet = new Set(feature.nodeIds);
  // Seeds: entry points if any, else the most-connected internal nodes
  let seeds = feature.entryPointIds.slice(0, 8);
  if (seeds.length === 0) {
    seeds = [...feature.nodeIds]
      .sort((a, b) => (downstream.get(b)?.length ?? 0) - (downstream.get(a)?.length ?? 0))
      .slice(0, 5);
  }

  const NODE_BUDGET = 18;
  const rendered = new Set<string>();
  const lines: string[] = [];
  const id = mermaidIds();
  const entrySet = new Set(feature.entryPointIds);
  const label = (nid: string) => {
    const n = nodeById.get(nid);
    if (!n) return nid;
    const r = routeText(n);
    // Mermaid line break is <br/>, not \n; show only the first route.
    return r && entrySet.has(nid) ? `${n.label}<br/>${r.split(',')[0].trim()}` : n.label;
  };

  const emitNode = (nid: string) => {
    const cls = entrySet.has(nid) ? ':::entry' : '';
    lines.push(`  ${id(nid)}["${mlabel(label(nid))}"]${cls}`);
  };

  let edgeCount = 0;
  for (const seed of seeds) {
    if (!nodeById.has(seed)) continue;
    if (!rendered.has(seed)) { rendered.add(seed); emitNode(seed); }
    for (const tgt of downstream.get(seed) ?? []) {
      if (rendered.size >= NODE_BUDGET) break;
      const tFeat = featureByNode.get(tgt);
      if (tFeat && tFeat !== feature.id && tFeat !== SHARED_ID) {
        // Collapse cross-feature target to a single boundary node
        const bkey = `feat:${tFeat}`;
        if (!rendered.has(bkey)) {
          rendered.add(bkey);
          lines.push(`  ${id(bkey)}(["▶ ${mlabel(nameById.get(tFeat) ?? tFeat)}"]):::boundary`);
        }
        lines.push(`  ${id(seed)} --> ${id(bkey)}`);
        edgeCount++;
      } else if (memberSet.has(tgt)) {
        if (!rendered.has(tgt)) { rendered.add(tgt); emitNode(tgt); }
        lines.push(`  ${id(seed)} --> ${id(tgt)}`);
        edgeCount++;
      }
    }
  }

  if (edgeCount === 0) return [];
  return [
    '```mermaid',
    'flowchart TD',
    ...lines,
    '  classDef entry fill:#4a90e8,color:#fff,stroke:#333;',
    '  classDef boundary fill:#2d2d44,color:#9ecbff,stroke:#4a90e8,stroke-dasharray:3 2;',
    '```',
  ];
}

function renderFeature(
  feature: FeatureGroup,
  nodeById: Map<string, OmniNode>,
  featureByNode: Map<string, string>,
  nameById: Map<string, string>,
  deps: Map<string, CrossDeps>,
  downstream: Map<string, string[]>,
): string {
  const L: string[] = [];
  L.push(`# ${feature.name}`);
  L.push('');
  L.push(summarize(feature));
  L.push('');
  L.push(`| Files | Routes | Data entities | Derived from |`);
  L.push(`| ---: | ---: | ---: | --- |`);
  L.push(`| ${feature.stats.nodes} | ${feature.stats.routes} | ${feature.stats.entities} | ${feature.source} |`);
  L.push('');

  // ── Routes ──
  if (feature.entryPointIds.length > 0) {
    L.push('## Routes');
    L.push('');
    for (const id of feature.entryPointIds) {
      const n = nodeById.get(id);
      if (!n) continue;
      const r = routeText(n);
      L.push(`- ${r ? `\`${cell(r)}\` — ` : ''}${cell(n.label)}`);
    }
    L.push('');
  }

  // ── Dependencies ──
  const d = deps.get(feature.id);
  const dependsOn = d ? rankDeps(d.dependsOn) : [];
  const usedBy = d ? rankDeps(d.usedBy) : [];
  if (dependsOn.length || usedBy.length) {
    L.push('## Dependencies');
    L.push('');
    const featLink = (id: string) => id.replace(/^feature-/, '') + '.md';
    if (dependsOn.length) {
      L.push('**Depends on:** ' + dependsOn
        .map(([id, c]) => `[${nameById.get(id) ?? id}](${featLink(id)}) (${c})`)
        .join(', '));
      L.push('');
    }
    if (usedBy.length) {
      L.push('**Used by:** ' + usedBy
        .map(([id, c]) => `[${nameById.get(id) ?? id}](${featLink(id)}) (${c})`)
        .join(', '));
      L.push('');
    }
  }

  // ── Flow diagram ──
  const flow = featureFlowchart(feature, nodeById, featureByNode, nameById, downstream);
  if (flow.length) {
    L.push('## Flow');
    L.push('');
    L.push(...flow);
    L.push('');
  }

  // ── Files (grouped by type) ──
  L.push('## Files');
  L.push('');
  const byType = new Map<string, OmniNode[]>();
  for (const id of feature.nodeIds) {
    const n = nodeById.get(id);
    if (!n) continue;
    if (!byType.has(n.type)) byType.set(n.type, []);
    byType.get(n.type)!.push(n);
  }
  const PER_TYPE = 25;
  for (const [type, ns] of [...byType.entries()].sort((a, b) => b[1].length - a[1].length)) {
    ns.sort((a, b) => a.label.localeCompare(b.label));
    L.push(`**${type}** (${ns.length})`);
    L.push('');
    for (const n of ns.slice(0, PER_TYPE)) L.push(`- ${cell(n.label)}`);
    if (ns.length > PER_TYPE) L.push(`- _…and ${ns.length - PER_TYPE} more_`);
    L.push('');
  }
  return L.join('\n');
}

function buildManifest(
  model: FeatureModel,
  nodeById: Map<string, OmniNode>,
  nameById: Map<string, string>,
  deps: Map<string, CrossDeps>,
): string {
  const features = model.features.map(f => {
    const d = deps.get(f.id);
    return {
      id: f.id,
      name: f.name,
      slug: f.slug,
      source: f.source,
      stats: f.stats,
      entryPoints: f.entryPointIds.map(id => {
        const n = nodeById.get(id);
        return { file: id, label: n?.label ?? '', route: n ? routeText(n) : '' };
      }),
      dependsOn: d ? rankDeps(d.dependsOn).map(([id, count]) => ({ feature: id, name: nameById.get(id) ?? id, count })) : [],
      usedBy: d ? rankDeps(d.usedBy).map(([id, count]) => ({ feature: id, name: nameById.get(id) ?? id, count })) : [],
      nodeIds: f.nodeIds,
    };
  });
  return JSON.stringify({ tool: 'omnigraph', features, shared: model.shared, ungrouped: model.ungrouped }, null, 2) + '\n';
}

// ─── Entry point ────────────────────────────────────────────────────

export function generateFeatureDocs(graph: OmniGraph): DocFile[] {
  const model = graph.features ?? detectFeatures(graph);
  const nodeById = new Map(graph.nodes.map(n => [n.id, n]));

  // nodeId → featureId (real features + shared), and featureId → display name
  const featureByNode = new Map<string, string>();
  const nameById = new Map<string, string>();
  for (const f of model.features) {
    nameById.set(f.id, f.name);
    for (const id of f.nodeIds) featureByNode.set(id, f.id);
  }
  for (const id of model.shared) featureByNode.set(id, SHARED_ID);

  // Downstream adjacency (source → targets), for per-feature flow diagrams
  const downstream = new Map<string, string[]>();
  for (const e of graph.edges) {
    if (!downstream.has(e.source)) downstream.set(e.source, []);
    downstream.get(e.source)!.push(e.target);
  }

  const deps = computeCrossDeps(graph, featureByNode);

  const files: DocFile[] = [];
  files.push({ path: 'README.md', content: renderIndex(model, nameById, deps) });
  for (const f of model.features) {
    files.push({
      path: `features/${keyOf(f)}.md`,
      content: renderFeature(f, nodeById, featureByNode, nameById, deps, downstream),
    });
  }
  files.push({ path: 'features.json', content: buildManifest(model, nodeById, nameById, deps) });
  return files;
}
